#!/bin/bash

# Format rules to confom to COMP1511 style
# Function to format .c (or .cpp?) file to COMP1511 style.
format_c() {
  # Check if clang-format is installed
  if ! command -v clang-format &> /dev/null; then
    echo "clang-format could not be found, please install it first."
    exit 1
  fi

  local filename="$1"

  if [ ! -f "$filename" ]; then
    echo "File '$filename' does not exist."
    exit 1
  fi

  clang-format -i "$filename" --style="{
    BasedOnStyle: LLVM,
    AlignAfterOpenBracket: Align,
    AlignOperands: Align,
    BreakBeforeBinaryOperators: true,
    AllowAllArgumentsOnNextLine: false,
    AllowAllParametersOfDeclarationOnNextLine: false,
    AllowShortBlocksOnASingleLine: Never,
    AllowShortEnumsOnASingleLine: false,
    AllowShortFunctionsOnASingleLine: None,
    AllowShortIfStatementsOnASingleLine: Never,
    BinPackArguments: false,
    BinPackParameters: false,
    BreakBeforeBinaryOperators: All,
    BreakBeforeBraces: Attach,
    BreakStringLiterals: true,
    ColumnLimit: 80,
    IndentWidth: 4,
    IndentWrappedFunctionNames: true,
    MaxEmptyLinesToKeep: 2,
    PointerAlignment: Right,
    ReflowComments: true,
    SpaceAfterCStyleCast: true,
    SpaceAfterLogicalNot: false,
    SpaceBeforeCpp11BracedList: true,
  }"
}

format_asm() {
  if [ ! -f "$filename" ]; then
    echo "File '$filename' does not exist."
    exit 1
  fi

  local filename="$1"

  # Check if python3 is installed
  if ! command -v python3 &> /dev/null; then
    echo "python3 could not be found, please install it first."
    exit 1
  fi

  # Get the directory of the currently executing script
  local DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  # Assume the location of mips_formatter relative to this script
  formatter_path="$DIR/../mips_formatter"

  python3 "$formatter_path"/main.py "$filename"
}

# Function to find the most recently modified .c file
find_latest_c_or_asm_file() {
  # Current directory only
  # find . -maxdepth 1 \( -name "*.c" -o -name "*.asm" -o -name "*.s" \) -printf '%T@ %p\n' \
  #   | sort -k1,1nr \
  #   | awk '{print substr($0, index($0,$2))}' \
  #   | head -n 1

  # Every directory
  find ~/_ \( -name "*.c" -o -name "*.asm" -o -name "*.s" \) -printf '%T@ %p\n' \
    | sort -k1,1nr \
    | awk '{print substr($0, index($0,$2))}' \
    | head -n 1
}

# _____________________________________________________________________________
# Main script logic


# Determine the args
if [ $# -gt 0 ]; then
  filename="$1"
else
  filename=$(find_latest_c_or_asm_file)

  if [ -z "$filename" ]; then
    echo "No .c, .asm, or .s files found."
    exit 1
  fi
fi

# Run the right format
if [[ "$filename" == *.c ]]; then
  format_c "$filename"
elif [[ $filename == *.s ]] || [[ $filename == *.asm ]]; then
  format_asm "$filename"
else
  echo "Filename is neither .c, .asm, nor .s."
  exit 1
fi

exit 0
